export default obj = {
  originalQuery: "justin+bieber",
  correctedQuery: "justin+bieber",
  results: 60124253,
  activeFilters: [
    {
      name: "Relevance",
      active: true,
      url: null,
      description: "Sort by relevance",
    },
  ],
  refinements: [],
  items: [
    {
      type: "video",
      title: "Justin Bieber - Ghost",
      id: "Fp8msa5uYsc",
      url: "https://www.youtube.com/watch?v=Fp8msa5uYsc",
      bestThumbnail: {
        url: "https://i.ytimg.com/vi/Fp8msa5uYsc/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBy5JMMfllCtppR2CS4kx_WHgzEZg",
        width: 720,
        height: 404,
      },
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/Fp8msa5uYsc/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBy5JMMfllCtppR2CS4kx_WHgzEZg",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/Fp8msa5uYsc/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDMsVAYqU5pE9fswJyGq_QhhRsfzw",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: ["CC"],
      author: {
        name: "Justin Bieber",
        channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
        url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: null,
      views: 275149372,
      duration: "3:33",
      uploadedAt: "1 year ago",
    },
    {
      type: "video",
      title: "Justin Bieber - Peaches ft. Daniel Caesar, Giveon",
      id: "tQ0yjYUFKAE",
      url: "https://www.youtube.com/watch?v=tQ0yjYUFKAE",
      bestThumbnail: {
        url: "https://i.ytimg.com/vi/tQ0yjYUFKAE/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC0VM5eqzf0t-LYhkYTP9XlcMkZfQ",
        width: 720,
        height: 404,
      },
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/tQ0yjYUFKAE/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC0VM5eqzf0t-LYhkYTP9XlcMkZfQ",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/tQ0yjYUFKAE/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLB7kZWK4H36Qr84b8i8Cpj6h-R3pg",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: ["CC"],
      author: {
        name: "Justin Bieber",
        channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
        url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: null,
      views: 661602408,
      duration: "3:18",
      uploadedAt: "2 years ago",
    },
    {
      type: "video",
      title: "The Kid LAROI, Justin Bieber - STAY (Official Video)",
      id: "kTJczUoc26U",
      url: "https://www.youtube.com/watch?v=kTJczUoc26U",
      bestThumbnail: {
        url: "https://i.ytimg.com/vi/kTJczUoc26U/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAdKxlnRLEpNZ-9tUtx61gfWBpO7A",
        width: 720,
        height: 404,
      },
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/kTJczUoc26U/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAdKxlnRLEpNZ-9tUtx61gfWBpO7A",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/kTJczUoc26U/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCW-ttLjyTn0ct_MkJXHky4JeAvjg",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: ["4K", "CC"],
      author: {
        name: "The Kid LAROI.",
        channelID: "UC6G2vAJrt407lwiynW116Eg",
        url: "https://www.youtube.com/channel/UC6G2vAJrt407lwiynW116Eg",
        bestAvatar: {
          url: "https://yt3.ggpht.com/pFqjym2DvgUcYlETC2gq7UXdaluBV0owo35i426akAyJ8djLvS6fbqPdjggCn4bRGoG3JHLW1qs=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/pFqjym2DvgUcYlETC2gq7UXdaluBV0owo35i426akAyJ8djLvS6fbqPdjggCn4bRGoG3JHLW1qs=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: null,
      views: 754784835,
      duration: "2:38",
      uploadedAt: "1 year ago",
    },
    {
      type: "video",
      title:
        "Justin Bieber - Intentions (Official Video (Short Version)) ft. Quavo",
      id: "3AyMjyHu1bA",
      url: "https://www.youtube.com/watch?v=3AyMjyHu1bA",
      bestThumbnail: {
        url: "https://i.ytimg.com/vi/3AyMjyHu1bA/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCWpPMJOTU780p8wlkVOWDo2p_nhQ",
        width: 720,
        height: 404,
      },
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/3AyMjyHu1bA/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCWpPMJOTU780p8wlkVOWDo2p_nhQ",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/3AyMjyHu1bA/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAC4OVDDFL_ttY6Y3pWwr3269Q9LA",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: ["CC"],
      author: {
        name: "Justin Bieber",
        channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
        url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: null,
      views: 626774675,
      duration: "3:45",
      uploadedAt: "3 years ago",
    },
    {
      type: "video",
      title:
        "Best of Justin Bieber 2022   Justin Bieber Greatest Hits Full Album 2022",
      id: "pPjaM99O0OY",
      url: "https://www.youtube.com/watch?v=pPjaM99O0OY",
      bestThumbnail: {
        url: "https://i.ytimg.com/vi/pPjaM99O0OY/hq720.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGAHwAQH4Af4JgALQBYoCDAgAEAEYZSBUKGIwDw==&rs=AOn4CLBUfijYaqER8EZi4QRshiPh1xrPzQ",
        width: 720,
        height: 404,
      },
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/pPjaM99O0OY/hq720.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGAHwAQH4Af4JgALQBYoCDAgAEAEYZSBUKGIwDw==&rs=AOn4CLBUfijYaqER8EZi4QRshiPh1xrPzQ",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/pPjaM99O0OY/hq720.jpg?sqp=-oaymwE9COgCEMoBSFryq4qpAy8IARUAAAAAGAElAADIQj0AgKJDeAHwAQH4Af4JgALQBYoCDAgAEAEYZSBUKGIwDw==&rs=AOn4CLDj46iCjgaVeB6_zGmwC_wdsTSXxw",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: [],
      author: {
        name: "Music LoyTroy",
        channelID: "UC9enO-No2yIhd3Rbcog4dHw",
        url: "https://www.youtube.com/@Loytroymusic",
        bestAvatar: {
          url: "https://yt3.ggpht.com/g5snfWpew5CplorCD2XE__1hG-OsCGe_fnB0EAJE699_2lo-8x_a-U_Pv5WM-X1XhurQutEUvrc=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/g5snfWpew5CplorCD2XE__1hG-OsCGe_fnB0EAJE699_2lo-8x_a-U_Pv5WM-X1XhurQutEUvrc=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
        verified: false,
      },
      description: null,
      views: 3797750,
      duration: "1:29:29",
      uploadedAt: "10 months ago",
    },
    {
      type: "video",
      title: "Justin Bieber - Baby ft. Ludacris",
      id: "kffacxfA7G4",
      url: "https://www.youtube.com/watch?v=kffacxfA7G4",
      bestThumbnail: {
        url: "https://i.ytimg.com/vi/kffacxfA7G4/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDm7Ja321NYzKF9nvMQTAK53jsmMw",
        width: 720,
        height: 404,
      },
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/kffacxfA7G4/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDm7Ja321NYzKF9nvMQTAK53jsmMw",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/kffacxfA7G4/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAUKBrATo9H3qXlOnjg4WBXST2PCg",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: ["4K", "CC"],
      author: {
        name: "Justin Bieber",
        channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
        url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: null,
      views: 2977902068,
      duration: "3:40",
      uploadedAt: "13 years ago",
    },
    {
      type: "video",
      title:
        "Hailey Bieber AMEAÇANDO LARGAR JUSTIN BIEBER! Zayn & Harry Styles JUNTOS! Taylor Swift FEZ ISSO...",
      id: "JYBVa_YKm5U",
      url: "https://www.youtube.com/watch?v=JYBVa_YKm5U",
      bestThumbnail: {
        url: "https://i.ytimg.com/vi/JYBVa_YKm5U/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC2yxG_teGHDh7YLdmDrFB-DPdY_Q",
        width: 720,
        height: 404,
      },
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/JYBVa_YKm5U/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC2yxG_teGHDh7YLdmDrFB-DPdY_Q",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/JYBVa_YKm5U/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBFxm6ee46TEqbenf2G4C5woX_r5g",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: ["New"],
      author: {
        name: "Rivernauty",
        channelID: "UCIuqyAaBuKK6evBq5aNyhOg",
        url: "https://www.youtube.com/@Rivernauty",
        bestAvatar: {
          url: "https://yt3.ggpht.com/fKcwVTIFcXEj3gxviNqwyGfNT0GcB8yLXiqYpiImbOXOpqAfRKfseq9XmGrWnpxB2Ascor_J=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/fKcwVTIFcXEj3gxviNqwyGfNT0GcB8yLXiqYpiImbOXOpqAfRKfseq9XmGrWnpxB2Ascor_J=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
        verified: false,
      },
      description: null,
      views: 4112,
      duration: "9:37",
      uploadedAt: "5 hours ago",
    },
    {
      type: "video",
      title: "Justin Bieber - What Do You Mean?",
      id: "DK_0jXPuIr0",
      url: "https://www.youtube.com/watch?v=DK_0jXPuIr0",
      bestThumbnail: {
        url: "https://i.ytimg.com/vi/DK_0jXPuIr0/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBKdi5r0rQbIk_zcUKGyCFB8DyRyA",
        width: 720,
        height: 404,
      },
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/DK_0jXPuIr0/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBKdi5r0rQbIk_zcUKGyCFB8DyRyA",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/DK_0jXPuIr0/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAd1vkMS6YbpTyZkjzM1IkDIPFACQ",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: ["CC"],
      author: {
        name: "Justin Bieber",
        channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
        url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: null,
      views: 2229703626,
      duration: "4:58",
      uploadedAt: "7 years ago",
    },
    {
      type: "channel",
      name: "Justin Bieber",
      channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
      url: "https://www.youtube.com/@justinbieber",
      bestAvatar: {
        url: "https://yt3.googleusercontent.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s176-c-k-c0x00ffffff-no-rj-mo",
        width: 176,
        height: 176,
      },
      avatars: [
        {
          url: "https://yt3.googleusercontent.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s176-c-k-c0x00ffffff-no-rj-mo",
          width: 176,
          height: 176,
        },
        {
          url: "https://yt3.googleusercontent.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj-mo",
          width: 88,
          height: 88,
        },
      ],
      verified: true,
      subscribers: "@justinbieber",
      descriptionShort:
        "Help change the world. JUSTICE the album out now https://JustinBieber.lnk.to/Justice.",
      videos: 715,
    },
    {
      type: "video",
      title: "Justin Bieber - Sorry (PURPOSE : The Movement)",
      id: "fRh_vgS2dFE",
      url: "https://www.youtube.com/watch?v=fRh_vgS2dFE",
      bestThumbnail: {
        url: "https://i.ytimg.com/vi/fRh_vgS2dFE/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCHCxpUdLkN8JYEBkn8r1j8SKg0gw",
        width: 720,
        height: 404,
      },
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/fRh_vgS2dFE/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCHCxpUdLkN8JYEBkn8r1j8SKg0gw",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/fRh_vgS2dFE/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCLZ0L7UUUGI3CrjSDjADoSAfnAog",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: ["CC"],
      author: {
        name: "Justin Bieber",
        channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
        url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: null,
      views: 3674922205,
      duration: "3:26",
      uploadedAt: "7 years ago",
    },
    {
      type: "video",
      title:
        ".J.u.s.t.i.n B.i.e.b.e.r Full Album . J.u.s.t.i.n.B.i.e.b.e.r Greatest Hits 2021",
      id: "dTZg6_uZp6o",
      url: "https://www.youtube.com/watch?v=dTZg6_uZp6o",
      bestThumbnail: {
        url: "https://i.ytimg.com/vi/dTZg6_uZp6o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB4E5cf6j3ZUZRX-V5r0prQii1ipA",
        width: 720,
        height: 404,
      },
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/dTZg6_uZp6o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB4E5cf6j3ZUZRX-V5r0prQii1ipA",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/dTZg6_uZp6o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBr26J0DXexiAN6QSnyn1eBY03MuQ",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: [],
      author: {
        name: "BEST SONGS COLLECTION",
        channelID: "UCrSoH8qhLQrYstaN7Zv-7Fg",
        url: "https://www.youtube.com/@bestsongscollection1731",
        bestAvatar: {
          url: "https://yt3.ggpht.com/2uO_LRiYYv4ZYmCiQZp3MTgq62qNYVmmu8zxjUPcWaqgO0nUTQwIAIZAaWD6HRe6j5Cpv5FQPYU=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/2uO_LRiYYv4ZYmCiQZp3MTgq62qNYVmmu8zxjUPcWaqgO0nUTQwIAIZAaWD6HRe6j5Cpv5FQPYU=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
        verified: false,
      },
      description: null,
      views: 28803,
      duration: "2:07:31",
      uploadedAt: "2 years ago",
    },
    {
      type: "video",
      title:
        "Justin Bieber Speaks On Hailey Trying to Put Him Under CONSERVATORSHIP",
      id: "ZVkmIyqS96I",
      url: "https://www.youtube.com/watch?v=ZVkmIyqS96I",
      bestThumbnail: {
        url: "https://i.ytimg.com/vi/ZVkmIyqS96I/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAlNqr-no0twMRNmOjwU00qwxIfig",
        width: 720,
        height: 404,
      },
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/ZVkmIyqS96I/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAlNqr-no0twMRNmOjwU00qwxIfig",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/ZVkmIyqS96I/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBKs6nn3cJw62pJST4TXZVq3cm72g",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: ["New"],
      author: {
        name: "This Happened",
        channelID: "UCylyoo597NuFFyJS_HwHubQ",
        url: "https://www.youtube.com/@thishappened1592",
        bestAvatar: {
          url: "https://yt3.ggpht.com/vSjRLrQ5x1Ru_7HSCNmX39LCh9RGkkProND-rePmNvDKdm_QFjRBcqSjJGi1AAVf7-mEPPOa=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/vSjRLrQ5x1Ru_7HSCNmX39LCh9RGkkProND-rePmNvDKdm_QFjRBcqSjJGi1AAVf7-mEPPOa=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Verified"],
        verified: true,
      },
      description: null,
      views: 34526,
      duration: "8:20",
      uploadedAt: "14 hours ago",
    },
    {
      type: "shelf",
      title: "People also watched",
      items: [
        {
          type: "video",
          title:
            "JustinBieber - Greatest Hits 2022 | TOP 100 Songs of the Weeks 2022 - Best Playlist Full Album",
          id: "gP9yCQf9x7M",
          url: "https://www.youtube.com/watch?v=gP9yCQf9x7M",
          bestThumbnail: {
            url: "https://i.ytimg.com/vi/gP9yCQf9x7M/hq720.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGAHwAQH4Af4JgALQBYoCDAgAEAEYMSBiKGUwDw==&rs=AOn4CLDP5L-mz8cwKI_aO2WQPdFyj0jBjA",
            width: 720,
            height: 404,
          },
          thumbnails: [
            {
              url: "https://i.ytimg.com/vi/gP9yCQf9x7M/hq720.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGAHwAQH4Af4JgALQBYoCDAgAEAEYMSBiKGUwDw==&rs=AOn4CLDP5L-mz8cwKI_aO2WQPdFyj0jBjA",
              width: 720,
              height: 404,
            },
            {
              url: "https://i.ytimg.com/vi/gP9yCQf9x7M/hq720.jpg?sqp=-oaymwE9COgCEMoBSFryq4qpAy8IARUAAAAAGAElAADIQj0AgKJDeAHwAQH4Af4JgALQBYoCDAgAEAEYMSBiKGUwDw==&rs=AOn4CLCEiK0mGEh6TWNPSML_cG-782MuoQ",
              width: 360,
              height: 202,
            },
          ],
          isUpcoming: false,
          upcoming: null,
          isLive: false,
          badges: [],
          author: {
            name: "Pop Music",
            channelID: "UCN1KgmdoHshpsbTNRSTesvA",
            url: "https://www.youtube.com/@popmusic9673",
            bestAvatar: {
              url: "https://yt3.ggpht.com/azlrpLBuLzgNrwJkFc7HG4pqi9ojjR6hwgiS4X3W5GTbn9NHodcyZfyNzK5R-0Orx6zKqPALbw=s68-c-k-c0x00ffffff-no-rj",
              width: 68,
              height: 68,
            },
            avatars: [
              {
                url: "https://yt3.ggpht.com/azlrpLBuLzgNrwJkFc7HG4pqi9ojjR6hwgiS4X3W5GTbn9NHodcyZfyNzK5R-0Orx6zKqPALbw=s68-c-k-c0x00ffffff-no-rj",
                width: 68,
                height: 68,
              },
            ],
            ownerBadges: [],
            verified: false,
          },
          description: null,
          views: 761832,
          duration: "1:38:12",
          uploadedAt: "1 year ago",
        },
        {
          type: "video",
          title:
            "Justin Bieber Opens The Door For His Friend, But Not For Hailey While Leaving Lunch At Great White",
          id: "QSxV808jqyU",
          url: "https://www.youtube.com/watch?v=QSxV808jqyU",
          bestThumbnail: {
            url: "https://i.ytimg.com/vi/QSxV808jqyU/hq720_2.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGADwAQH4Ad4EgAK4CIoCDAgAEAEYZiBmKGYwDw==&rs=AOn4CLAM5mCRAgejRgxmBLd7dF-PORpOyQ",
            width: 720,
            height: 404,
          },
          thumbnails: [
            {
              url: "https://i.ytimg.com/vi/QSxV808jqyU/hq720_2.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGADwAQH4Ad4EgAK4CIoCDAgAEAEYZiBmKGYwDw==&rs=AOn4CLAM5mCRAgejRgxmBLd7dF-PORpOyQ",
              width: 720,
              height: 404,
            },
            {
              url: "https://i.ytimg.com/vi/QSxV808jqyU/hq720_2.jpg?sqp=-oaymwE9COgCEMoBSFryq4qpAy8IARUAAAAAGAAlAADIQj0AgKJDeAHwAQH4Ad4EgAK4CIoCDAgAEAEYZiBmKGYwDw==&rs=AOn4CLC7oB7rXpEwEMR3C33KzATD9ZNsaw",
              width: 360,
              height: 202,
            },
          ],
          isUpcoming: false,
          upcoming: null,
          isLive: false,
          badges: ["New"],
          author: {
            name: "The Hollywood Fix",
            channelID: "UCTnFdC5jhEClcYhTn9wo-VQ",
            url: "https://www.youtube.com/@TheHollywoodFix",
            bestAvatar: {
              url: "https://yt3.ggpht.com/ytc/AGIKgqNhSktavLAc05D4fBwAS0B6SQqnYlwzt6kcnzGoRQ=s68-c-k-c0x00ffffff-no-rj",
              width: 68,
              height: 68,
            },
            avatars: [
              {
                url: "https://yt3.ggpht.com/ytc/AGIKgqNhSktavLAc05D4fBwAS0B6SQqnYlwzt6kcnzGoRQ=s68-c-k-c0x00ffffff-no-rj",
                width: 68,
                height: 68,
              },
            ],
            ownerBadges: ["Verified"],
            verified: true,
          },
          description: null,
          views: 17032,
          duration: "0:54",
          uploadedAt: "9 hours ago",
        },
        {
          type: "video",
          title:
            "Justin Bieber Opens The Door For His Friend, But Not For Hailey While Leaving Lunch At Great White",
          id: "LGtDKEVOndU",
          url: "https://www.youtube.com/watch?v=LGtDKEVOndU",
          bestThumbnail: {
            url: "https://i.ytimg.com/vi/LGtDKEVOndU/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDL1oa5MjpsFnINLvvVhkXJ5eEp0A",
            width: 720,
            height: 404,
          },
          thumbnails: [
            {
              url: "https://i.ytimg.com/vi/LGtDKEVOndU/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDL1oa5MjpsFnINLvvVhkXJ5eEp0A",
              width: 720,
              height: 404,
            },
            {
              url: "https://i.ytimg.com/vi/LGtDKEVOndU/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA1aqWR6vGKUE-9uclDLpHOPyRM6w",
              width: 360,
              height: 202,
            },
          ],
          isUpcoming: false,
          upcoming: null,
          isLive: false,
          badges: ["New"],
          author: {
            name: "The Hollywood Fix",
            channelID: "UCTnFdC5jhEClcYhTn9wo-VQ",
            url: "https://www.youtube.com/@TheHollywoodFix",
            bestAvatar: {
              url: "https://yt3.ggpht.com/ytc/AGIKgqNhSktavLAc05D4fBwAS0B6SQqnYlwzt6kcnzGoRQ=s68-c-k-c0x00ffffff-no-rj",
              width: 68,
              height: 68,
            },
            avatars: [
              {
                url: "https://yt3.ggpht.com/ytc/AGIKgqNhSktavLAc05D4fBwAS0B6SQqnYlwzt6kcnzGoRQ=s68-c-k-c0x00ffffff-no-rj",
                width: 68,
                height: 68,
              },
            ],
            ownerBadges: ["Verified"],
            verified: true,
          },
          description: null,
          views: 8844,
          duration: "1:02",
          uploadedAt: "10 hours ago",
        },
        {
          type: "video",
          title: "Justin Bieber - Hold On",
          id: "LWeiydKl0mU",
          url: "https://www.youtube.com/watch?v=LWeiydKl0mU",
          bestThumbnail: {
            url: "https://i.ytimg.com/vi/LWeiydKl0mU/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLD5E0vN6VDfvtqXmjOb2IaoHL_9Mw",
            width: 720,
            height: 404,
          },
          thumbnails: [
            {
              url: "https://i.ytimg.com/vi/LWeiydKl0mU/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLD5E0vN6VDfvtqXmjOb2IaoHL_9Mw",
              width: 720,
              height: 404,
            },
            {
              url: "https://i.ytimg.com/vi/LWeiydKl0mU/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBEDWaKV50sDpNOelc1g3gHx9kkjA",
              width: 360,
              height: 202,
            },
          ],
          isUpcoming: false,
          upcoming: null,
          isLive: false,
          badges: ["4K", "CC"],
          author: {
            name: "Justin Bieber",
            channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
            url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
            bestAvatar: {
              url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
              width: 68,
              height: 68,
            },
            avatars: [
              {
                url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
                width: 68,
                height: 68,
              },
            ],
            ownerBadges: ["Official Artist Channel"],
            verified: true,
          },
          description: null,
          views: 95735046,
          duration: "5:09",
          uploadedAt: "2 years ago",
        },
        {
          type: "video",
          title: "will.i.am - #thatPOWER ft. Justin Bieber",
          id: "DGIgXP9SvB8",
          url: "https://www.youtube.com/watch?v=DGIgXP9SvB8",
          bestThumbnail: {
            url: "https://i.ytimg.com/vi/DGIgXP9SvB8/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDdcvrDiNkY1EF8V2TlQsq0XKroaA",
            width: 720,
            height: 404,
          },
          thumbnails: [
            {
              url: "https://i.ytimg.com/vi/DGIgXP9SvB8/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDdcvrDiNkY1EF8V2TlQsq0XKroaA",
              width: 720,
              height: 404,
            },
            {
              url: "https://i.ytimg.com/vi/DGIgXP9SvB8/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLABwyVnEmBeYInaArPTSJkFpZJ-hA",
              width: 360,
              height: 202,
            },
          ],
          isUpcoming: false,
          upcoming: null,
          isLive: false,
          badges: ["CC"],
          author: {
            name: "will i am",
            channelID: "UCVCdOaiHD05nGQm9tf1SEzw",
            url: "https://www.youtube.com/channel/UCVCdOaiHD05nGQm9tf1SEzw",
            bestAvatar: {
              url: "https://yt3.ggpht.com/ytc/AGIKgqOgx1tMDW0kkWmI3OvssNjqkDdcDI1eUylSneeDtQ=s88-c-k-c0x00ffffff-no-rj",
              width: 68,
              height: 68,
            },
            avatars: [
              {
                url: "https://yt3.ggpht.com/ytc/AGIKgqOgx1tMDW0kkWmI3OvssNjqkDdcDI1eUylSneeDtQ=s88-c-k-c0x00ffffff-no-rj",
                width: 68,
                height: 68,
              },
            ],
            ownerBadges: ["Official Artist Channel"],
            verified: true,
          },
          description: null,
          views: 324313724,
          duration: "4:53",
          uploadedAt: "10 years ago",
        },
        {
          type: "video",
          title: "Sean Kingston, Justin Bieber - Eenie Meenie (Official Video)",
          id: "prmmCg5bKxA",
          url: "https://www.youtube.com/watch?v=prmmCg5bKxA",
          bestThumbnail: {
            url: "https://i.ytimg.com/vi/prmmCg5bKxA/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAb6JQEA6iv5lMXaU76PcZ5OAALtw",
            width: 720,
            height: 404,
          },
          thumbnails: [
            {
              url: "https://i.ytimg.com/vi/prmmCg5bKxA/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAb6JQEA6iv5lMXaU76PcZ5OAALtw",
              width: 720,
              height: 404,
            },
            {
              url: "https://i.ytimg.com/vi/prmmCg5bKxA/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAM-sWgzCO7-RBHYn8FDTdWzKLmYA",
              width: 360,
              height: 202,
            },
          ],
          isUpcoming: false,
          upcoming: null,
          isLive: false,
          badges: [],
          author: {
            name: "seankingston",
            channelID: "UCiAej2SO1sEdjj5S2RnbIhg",
            url: "https://www.youtube.com/channel/UCiAej2SO1sEdjj5S2RnbIhg",
            bestAvatar: {
              url: "https://yt3.ggpht.com/dwIMMpjXhRnnl3cpOcCTd0RC8CSGCN4JvHbAKUfFA4vYy1G5rCQVtKMqMZg6FeoxZh2ynkW8sig=s88-c-k-c0x00ffffff-no-rj",
              width: 68,
              height: 68,
            },
            avatars: [
              {
                url: "https://yt3.ggpht.com/dwIMMpjXhRnnl3cpOcCTd0RC8CSGCN4JvHbAKUfFA4vYy1G5rCQVtKMqMZg6FeoxZh2ynkW8sig=s88-c-k-c0x00ffffff-no-rj",
                width: 68,
                height: 68,
              },
            ],
            ownerBadges: ["Official Artist Channel"],
            verified: true,
          },
          description: null,
          views: 615953015,
          duration: "3:25",
          uploadedAt: "13 years ago",
        },
        {
          type: "video",
          title:
            'Skrillex and Diplo - "Where Are Ü Now" with Justin Bieber (Official Video)',
          id: "nntGTK2Fhb0",
          url: "https://www.youtube.com/watch?v=nntGTK2Fhb0",
          bestThumbnail: {
            url: "https://i.ytimg.com/vi/nntGTK2Fhb0/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAAnu3Xv6519hRoqbAHPrSUhcWRHQ",
            width: 480,
            height: 270,
          },
          thumbnails: [
            {
              url: "https://i.ytimg.com/vi/nntGTK2Fhb0/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAAnu3Xv6519hRoqbAHPrSUhcWRHQ",
              width: 480,
              height: 270,
            },
          ],
          isUpcoming: false,
          upcoming: null,
          isLive: false,
          badges: [],
          author: {
            name: "Jack Ü",
            channelID: "UCtuGozGshjqqErhHGEmHnJw",
            url: "https://www.youtube.com/channel/UCtuGozGshjqqErhHGEmHnJw",
            bestAvatar: {
              url: "https://yt3.ggpht.com/ytc/AGIKgqOYL0_H_IoVNDhMyRoxEX2gR-oYGIPQ6lR4VEjb=s88-c-k-c0x00ffffff-no-rj",
              width: 68,
              height: 68,
            },
            avatars: [
              {
                url: "https://yt3.ggpht.com/ytc/AGIKgqOYL0_H_IoVNDhMyRoxEX2gR-oYGIPQ6lR4VEjb=s88-c-k-c0x00ffffff-no-rj",
                width: 68,
                height: 68,
              },
            ],
            ownerBadges: ["Official Artist Channel"],
            verified: true,
          },
          description: null,
          views: 1246846842,
          duration: "4:12",
          uploadedAt: "7 years ago",
        },
        {
          type: "video",
          title: "Justin Bieber - As Long As You Love Me ft. Big Sean",
          id: "R4em3LKQCAQ",
          url: "https://www.youtube.com/watch?v=R4em3LKQCAQ",
          bestThumbnail: {
            url: "https://i.ytimg.com/vi/R4em3LKQCAQ/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBdjs4cywiuQN97igJzDJrlj1hfUA",
            width: 720,
            height: 404,
          },
          thumbnails: [
            {
              url: "https://i.ytimg.com/vi/R4em3LKQCAQ/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBdjs4cywiuQN97igJzDJrlj1hfUA",
              width: 720,
              height: 404,
            },
            {
              url: "https://i.ytimg.com/vi/R4em3LKQCAQ/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAj39OaV8RUkCWr2VX9Den1I6c69w",
              width: 360,
              height: 202,
            },
          ],
          isUpcoming: false,
          upcoming: null,
          isLive: false,
          badges: ["CC"],
          author: {
            name: "Justin Bieber",
            channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
            url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
            bestAvatar: {
              url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
              width: 68,
              height: 68,
            },
            avatars: [
              {
                url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
                width: 68,
                height: 68,
              },
            ],
            ownerBadges: ["Official Artist Channel"],
            verified: true,
          },
          description: null,
          views: 500324080,
          duration: "5:52",
          uploadedAt: "10 years ago",
        },
        {
          type: "video",
          title:
            "Chris Brown - Next To You (Official Music Video) ft. Justin Bieber",
          id: "EEuQU6a90Pc",
          url: "https://www.youtube.com/watch?v=EEuQU6a90Pc",
          bestThumbnail: {
            url: "https://i.ytimg.com/vi/EEuQU6a90Pc/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCsbuXvkjypnzUFL3ONdYyK0zgT4w",
            width: 720,
            height: 404,
          },
          thumbnails: [
            {
              url: "https://i.ytimg.com/vi/EEuQU6a90Pc/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCsbuXvkjypnzUFL3ONdYyK0zgT4w",
              width: 720,
              height: 404,
            },
            {
              url: "https://i.ytimg.com/vi/EEuQU6a90Pc/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDkWkA7oknRvsPkK-9CYyMhsrJzKQ",
              width: 360,
              height: 202,
            },
          ],
          isUpcoming: false,
          upcoming: null,
          isLive: false,
          badges: [],
          author: {
            name: "Chris Brown",
            channelID: "UCcYrdFJF7hmPXRNaWdrko4w",
            url: "https://www.youtube.com/channel/UCcYrdFJF7hmPXRNaWdrko4w",
            bestAvatar: {
              url: "https://yt3.ggpht.com/GsZL97F0oViK5VLMqNV2NM__L9Kf8uJLyEYhom90Mmw8Bl07C_rZsv7yItJRM04yngqyY1Sl=s88-c-k-c0x00ffffff-no-rj",
              width: 68,
              height: 68,
            },
            avatars: [
              {
                url: "https://yt3.ggpht.com/GsZL97F0oViK5VLMqNV2NM__L9Kf8uJLyEYhom90Mmw8Bl07C_rZsv7yItJRM04yngqyY1Sl=s88-c-k-c0x00ffffff-no-rj",
                width: 68,
                height: 68,
              },
            ],
            ownerBadges: ["Official Artist Channel"],
            verified: true,
          },
          description: null,
          views: 319616251,
          duration: "6:04",
          uploadedAt: "12 years ago",
        },
        {
          type: "video",
          title:
            "DJ Khaled - No Brainer (Official Video) ft. Justin Bieber, Chance the Rapper, Quavo",
          id: "kxloC1MKTpg",
          url: "https://www.youtube.com/watch?v=kxloC1MKTpg",
          bestThumbnail: {
            url: "https://i.ytimg.com/vi/kxloC1MKTpg/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLARqeT4KYpERUWCP0cvtTLQrqAT8g",
            width: 720,
            height: 404,
          },
          thumbnails: [
            {
              url: "https://i.ytimg.com/vi/kxloC1MKTpg/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLARqeT4KYpERUWCP0cvtTLQrqAT8g",
              width: 720,
              height: 404,
            },
            {
              url: "https://i.ytimg.com/vi/kxloC1MKTpg/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAiWCxe6WQZ79GEwIdQA2-FYlsY0A",
              width: 360,
              height: 202,
            },
          ],
          isUpcoming: false,
          upcoming: null,
          isLive: false,
          badges: ["4K", "CC"],
          author: {
            name: "DJ Khaled",
            channelID: "UC0Kgvj5t_c9EMWpEDWJuR1Q",
            url: "https://www.youtube.com/channel/UC0Kgvj5t_c9EMWpEDWJuR1Q",
            bestAvatar: {
              url: "https://yt3.ggpht.com/6rLXl36oQXNCCToi1s2nxiakGsiDlWpJmh0RIL8XQ-K2raRz28R4qSQN-yRqtSIDwR6fFt0i=s88-c-k-c0x00ffffff-no-rj",
              width: 68,
              height: 68,
            },
            avatars: [
              {
                url: "https://yt3.ggpht.com/6rLXl36oQXNCCToi1s2nxiakGsiDlWpJmh0RIL8XQ-K2raRz28R4qSQN-yRqtSIDwR6fFt0i=s88-c-k-c0x00ffffff-no-rj",
                width: 68,
                height: 68,
              },
            ],
            ownerBadges: ["Official Artist Channel"],
            verified: true,
          },
          description: null,
          views: 347625364,
          duration: "4:26",
          uploadedAt: "4 years ago",
        },
      ],
    },
    {
      type: "video",
      title: "Justin Bieber - Company",
      id: "gdx7gN1UyX0",
      url: "https://www.youtube.com/watch?v=gdx7gN1UyX0",
      bestThumbnail: {
        url: "https://i.ytimg.com/vi/gdx7gN1UyX0/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBaakJU1LRlg2WL1s3BXvishqMrBA",
        width: 720,
        height: 404,
      },
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/gdx7gN1UyX0/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBaakJU1LRlg2WL1s3BXvishqMrBA",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/gdx7gN1UyX0/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBEbdKFpMR_pBDnOMsQp253RYV0Tw",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: ["CC"],
      author: {
        name: "Justin Bieber",
        channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
        url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: null,
      views: 666335760,
      duration: "3:28",
      uploadedAt: "7 years ago",
    },
    {
      type: "video",
      title: "Justin Bieber - Anyone",
      id: "KIK3azN4w34",
      url: "https://www.youtube.com/watch?v=KIK3azN4w34",
      bestThumbnail: {
        url: "https://i.ytimg.com/vi/KIK3azN4w34/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCW9RPZitMoVWvnIgkAFvTvfuyxDA",
        width: 720,
        height: 404,
      },
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/KIK3azN4w34/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCW9RPZitMoVWvnIgkAFvTvfuyxDA",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/KIK3azN4w34/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDDlVHlRORF6KkyFE8ShrqwX3N0IA",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: ["4K", "CC"],
      author: {
        name: "Justin Bieber",
        channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
        url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: null,
      views: 107015659,
      duration: "4:24",
      uploadedAt: "2 years ago",
    },
    {
      type: "shelf",
      title: "Latest from Justin Bieber",
      items: [
        {
          type: "video",
          title: "Drew House TOKYO #shorts",
          id: "z5AIMF1BjOE",
          url: "https://www.youtube.com/watch?v=z5AIMF1BjOE",
          bestThumbnail: {
            url: "https://i.ytimg.com/vi/z5AIMF1BjOE/hq720.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGAHwAQH4AfoJgALQBYoCDAgAEAEYZSBWKEQwDw==&rs=AOn4CLBnABOBuL2eBDmfalRmtHRLfJOcog",
            width: 720,
            height: 404,
          },
          thumbnails: [
            {
              url: "https://i.ytimg.com/vi/z5AIMF1BjOE/hq720.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGAHwAQH4AfoJgALQBYoCDAgAEAEYZSBWKEQwDw==&rs=AOn4CLBnABOBuL2eBDmfalRmtHRLfJOcog",
              width: 720,
              height: 404,
            },
            {
              url: "https://i.ytimg.com/vi/z5AIMF1BjOE/hq720.jpg?sqp=-oaymwE9COgCEMoBSFryq4qpAy8IARUAAAAAGAElAADIQj0AgKJDeAHwAQH4AfoJgALQBYoCDAgAEAEYZSBWKEQwDw==&rs=AOn4CLBPLc0vEifE-fQJMhLESSOsI7uPNw",
              width: 360,
              height: 202,
            },
          ],
          isUpcoming: false,
          upcoming: null,
          isLive: false,
          badges: [],
          author: {
            name: "Justin Bieber",
            channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
            url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
            bestAvatar: {
              url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
              width: 68,
              height: 68,
            },
            avatars: [
              {
                url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
                width: 68,
                height: 68,
              },
            ],
            ownerBadges: ["Official Artist Channel"],
            verified: true,
          },
          description: null,
          views: 789367,
          duration: "0:42",
          uploadedAt: "7 months ago",
        },
        {
          type: "video",
          title:
            "Justin Bieber X Free Fire - Beautiful Love (Free Fire) [Official Video]",
          id: "_lpSCOZ1PCo",
          url: "https://www.youtube.com/watch?v=_lpSCOZ1PCo",
          bestThumbnail: {
            url: "https://i.ytimg.com/vi/_lpSCOZ1PCo/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB6hSCiKAY1p-wGMFH7T3r-m_HRYQ",
            width: 720,
            height: 404,
          },
          thumbnails: [
            {
              url: "https://i.ytimg.com/vi/_lpSCOZ1PCo/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB6hSCiKAY1p-wGMFH7T3r-m_HRYQ",
              width: 720,
              height: 404,
            },
            {
              url: "https://i.ytimg.com/vi/_lpSCOZ1PCo/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAgUj6J8nUCpV0aK2du5S7FA22QMQ",
              width: 360,
              height: 202,
            },
          ],
          isUpcoming: false,
          upcoming: null,
          isLive: false,
          badges: [],
          author: {
            name: "Justin Bieber",
            channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
            url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
            bestAvatar: {
              url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
              width: 68,
              height: 68,
            },
            avatars: [
              {
                url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
                width: 68,
                height: 68,
              },
            ],
            ownerBadges: ["Official Artist Channel"],
            verified: true,
          },
          description: null,
          views: 5433857,
          duration: "3:33",
          uploadedAt: "9 months ago",
        },
        {
          type: "video",
          title:
            "Justin Bieber, Don Toliver - The Making of 'Honest' (Vevo Footnotes)",
          id: "ZMH9AMwAk34",
          url: "https://www.youtube.com/watch?v=ZMH9AMwAk34",
          bestThumbnail: {
            url: "https://i.ytimg.com/vi/ZMH9AMwAk34/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDvpk9diNHfVy4UAehKvIgf8cH8nA",
            width: 720,
            height: 404,
          },
          thumbnails: [
            {
              url: "https://i.ytimg.com/vi/ZMH9AMwAk34/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDvpk9diNHfVy4UAehKvIgf8cH8nA",
              width: 720,
              height: 404,
            },
            {
              url: "https://i.ytimg.com/vi/ZMH9AMwAk34/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBjSMrUEBe1y-6sE_w_SraFWZDNWQ",
              width: 360,
              height: 202,
            },
          ],
          isUpcoming: false,
          upcoming: null,
          isLive: false,
          badges: ["CC"],
          author: {
            name: "Justin Bieber",
            channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
            url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
            bestAvatar: {
              url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
              width: 68,
              height: 68,
            },
            avatars: [
              {
                url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
                width: 68,
                height: 68,
              },
            ],
            ownerBadges: ["Official Artist Channel"],
            verified: true,
          },
          description: null,
          views: 3409588,
          duration: "3:32",
          uploadedAt: "1 year ago",
        },
        {
          type: "video",
          title: "#shorts",
          id: "-78y2WW4YDA",
          url: "https://www.youtube.com/watch?v=-78y2WW4YDA",
          bestThumbnail: {
            url: "https://i.ytimg.com/vi/-78y2WW4YDA/hq720_2.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGADwAQH4AZIDgALQBYoCDAgAEAEYfyATKBUwDw==&rs=AOn4CLD-zAjMLXEB06ij2xAIiwQyu7sA_Q",
            width: 720,
            height: 404,
          },
          thumbnails: [
            {
              url: "https://i.ytimg.com/vi/-78y2WW4YDA/hq720_2.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGADwAQH4AZIDgALQBYoCDAgAEAEYfyATKBUwDw==&rs=AOn4CLD-zAjMLXEB06ij2xAIiwQyu7sA_Q",
              width: 720,
              height: 404,
            },
            {
              url: "https://i.ytimg.com/vi/-78y2WW4YDA/hq720_2.jpg?sqp=-oaymwE9COgCEMoBSFryq4qpAy8IARUAAAAAGAAlAADIQj0AgKJDeAHwAQH4AZIDgALQBYoCDAgAEAEYfyATKBUwDw==&rs=AOn4CLDjwaG5z2P_P1HIu0RqbIEJBPCIkw",
              width: 360,
              height: 202,
            },
          ],
          isUpcoming: false,
          upcoming: null,
          isLive: false,
          badges: [],
          author: {
            name: "Justin Bieber",
            channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
            url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
            bestAvatar: {
              url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
              width: 68,
              height: 68,
            },
            avatars: [
              {
                url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
                width: 68,
                height: 68,
              },
            ],
            ownerBadges: ["Official Artist Channel"],
            verified: true,
          },
          description: null,
          views: 1221393,
          duration: "0:11",
          uploadedAt: "1 year ago",
        },
        {
          type: "video",
          title: "May 13, 2022",
          id: "UWrBS-4pSfM",
          url: "https://www.youtube.com/watch?v=UWrBS-4pSfM",
          bestThumbnail: {
            url: "https://i.ytimg.com/vi/UWrBS-4pSfM/hq720_2.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGADwAQH4AZQDgALQBYoCDAgAEAEYUyBVKGUwDw==&rs=AOn4CLCendbhDDTiLW7Crar7r5eOAgbVWw",
            width: 720,
            height: 404,
          },
          thumbnails: [
            {
              url: "https://i.ytimg.com/vi/UWrBS-4pSfM/hq720_2.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGADwAQH4AZQDgALQBYoCDAgAEAEYUyBVKGUwDw==&rs=AOn4CLCendbhDDTiLW7Crar7r5eOAgbVWw",
              width: 720,
              height: 404,
            },
            {
              url: "https://i.ytimg.com/vi/UWrBS-4pSfM/hq720_2.jpg?sqp=-oaymwE9COgCEMoBSFryq4qpAy8IARUAAAAAGAAlAADIQj0AgKJDeAHwAQH4AZQDgALQBYoCDAgAEAEYUyBVKGUwDw==&rs=AOn4CLBWHbMZaS26OUXOvfgEkKFqWHmtag",
              width: 360,
              height: 202,
            },
          ],
          isUpcoming: false,
          upcoming: null,
          isLive: false,
          badges: [],
          author: {
            name: "Justin Bieber",
            channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
            url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
            bestAvatar: {
              url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
              width: 68,
              height: 68,
            },
            avatars: [
              {
                url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
                width: 68,
                height: 68,
              },
            ],
            ownerBadges: ["Official Artist Channel"],
            verified: true,
          },
          description: null,
          views: 1204095,
          duration: "0:04",
          uploadedAt: "1 year ago",
        },
        {
          type: "video",
          title:
            "Justin Bieber - Honest (feat. Don Toliver) (Official Lyric Video)",
          id: "jur26nGiqOY",
          url: "https://www.youtube.com/watch?v=jur26nGiqOY",
          bestThumbnail: {
            url: "https://i.ytimg.com/vi/jur26nGiqOY/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB0nPMHEXXxvMk_2-VcWfJbehCN5g",
            width: 720,
            height: 404,
          },
          thumbnails: [
            {
              url: "https://i.ytimg.com/vi/jur26nGiqOY/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB0nPMHEXXxvMk_2-VcWfJbehCN5g",
              width: 720,
              height: 404,
            },
            {
              url: "https://i.ytimg.com/vi/jur26nGiqOY/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCtPO0LaluPCPRGWr4h2zTPP5R0Rw",
              width: 360,
              height: 202,
            },
          ],
          isUpcoming: false,
          upcoming: null,
          isLive: false,
          badges: [],
          author: {
            name: "Justin Bieber",
            channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
            url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
            bestAvatar: {
              url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
              width: 68,
              height: 68,
            },
            avatars: [
              {
                url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
                width: 68,
                height: 68,
              },
            ],
            ownerBadges: ["Official Artist Channel"],
            verified: true,
          },
          description: null,
          views: 2310112,
          duration: "3:14",
          uploadedAt: "1 year ago",
        },
        {
          type: "video",
          title: "Justin Bieber - Honest ft. Don Toliver",
          id: "n1khwOk5dN8",
          url: "https://www.youtube.com/watch?v=n1khwOk5dN8",
          bestThumbnail: {
            url: "https://i.ytimg.com/vi/n1khwOk5dN8/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDPXf_4-IpDlih41RDUyauqej2_jw",
            width: 720,
            height: 404,
          },
          thumbnails: [
            {
              url: "https://i.ytimg.com/vi/n1khwOk5dN8/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDPXf_4-IpDlih41RDUyauqej2_jw",
              width: 720,
              height: 404,
            },
            {
              url: "https://i.ytimg.com/vi/n1khwOk5dN8/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBEOINBL0fv3kN-nlJ4sgAaHOYzgQ",
              width: 360,
              height: 202,
            },
          ],
          isUpcoming: false,
          upcoming: null,
          isLive: false,
          badges: ["4K", "CC"],
          author: {
            name: "Justin Bieber",
            channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
            url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
            bestAvatar: {
              url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
              width: 68,
              height: 68,
            },
            avatars: [
              {
                url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
                width: 68,
                height: 68,
              },
            ],
            ownerBadges: ["Official Artist Channel"],
            verified: true,
          },
          description: null,
          views: 34314520,
          duration: "3:32",
          uploadedAt: "1 year ago",
        },
        {
          type: "video",
          title: "April 24, 2022",
          id: "Bv3LvcQjWlI",
          url: "https://www.youtube.com/watch?v=Bv3LvcQjWlI",
          bestThumbnail: {
            url: "https://i.ytimg.com/vi/Bv3LvcQjWlI/hq720_2.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGADwAQH4AZQDgALQBYoCDAgAEAEYRSBTKGUwDw==&rs=AOn4CLDoSKqmk7q50RBPEoi_xHSXi-_0DA",
            width: 720,
            height: 404,
          },
          thumbnails: [
            {
              url: "https://i.ytimg.com/vi/Bv3LvcQjWlI/hq720_2.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGADwAQH4AZQDgALQBYoCDAgAEAEYRSBTKGUwDw==&rs=AOn4CLDoSKqmk7q50RBPEoi_xHSXi-_0DA",
              width: 720,
              height: 404,
            },
            {
              url: "https://i.ytimg.com/vi/Bv3LvcQjWlI/hq720_2.jpg?sqp=-oaymwE9COgCEMoBSFryq4qpAy8IARUAAAAAGAAlAADIQj0AgKJDeAHwAQH4AZQDgALQBYoCDAgAEAEYRSBTKGUwDw==&rs=AOn4CLDDLcuYkdij6yXYwDvMoXpdfYFN-Q",
              width: 360,
              height: 202,
            },
          ],
          isUpcoming: false,
          upcoming: null,
          isLive: false,
          badges: [],
          author: {
            name: "Justin Bieber",
            channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
            url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
            bestAvatar: {
              url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
              width: 68,
              height: 68,
            },
            avatars: [
              {
                url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
                width: 68,
                height: 68,
              },
            ],
            ownerBadges: ["Official Artist Channel"],
            verified: true,
          },
          description: null,
          views: 1113836,
          duration: "0:13",
          uploadedAt: "1 year ago",
        },
        {
          type: "video",
          title: "Sometimes life slaps you in the face",
          id: "xVzJSUpp9L4",
          url: "https://www.youtube.com/watch?v=xVzJSUpp9L4",
          bestThumbnail: {
            url: "https://i.ytimg.com/vi/xVzJSUpp9L4/hq720_2.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGADwAQH4AZQDgALQBYoCDAgAEAEYZSBlKGUwDw==&rs=AOn4CLDhr4ne-ZFEsnUgrpguhAnx1n6rHQ",
            width: 720,
            height: 404,
          },
          thumbnails: [
            {
              url: "https://i.ytimg.com/vi/xVzJSUpp9L4/hq720_2.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGADwAQH4AZQDgALQBYoCDAgAEAEYZSBlKGUwDw==&rs=AOn4CLDhr4ne-ZFEsnUgrpguhAnx1n6rHQ",
              width: 720,
              height: 404,
            },
            {
              url: "https://i.ytimg.com/vi/xVzJSUpp9L4/hq720_2.jpg?sqp=-oaymwE9COgCEMoBSFryq4qpAy8IARUAAAAAGAAlAADIQj0AgKJDeAHwAQH4AZQDgALQBYoCDAgAEAEYZSBlKGUwDw==&rs=AOn4CLBzcz9aYYxCaRwJujaI-JJKhOhGZw",
              width: 360,
              height: 202,
            },
          ],
          isUpcoming: false,
          upcoming: null,
          isLive: false,
          badges: [],
          author: {
            name: "Justin Bieber",
            channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
            url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
            bestAvatar: {
              url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
              width: 68,
              height: 68,
            },
            avatars: [
              {
                url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
                width: 68,
                height: 68,
              },
            ],
            ownerBadges: ["Official Artist Channel"],
            verified: true,
          },
          description: null,
          views: 759034,
          duration: "0:06",
          uploadedAt: "1 year ago",
        },
        {
          type: "video",
          title: "Come into my world 🌎",
          id: "Zxxl386UQqo",
          url: "https://www.youtube.com/watch?v=Zxxl386UQqo",
          bestThumbnail: {
            url: "https://i.ytimg.com/vi/Zxxl386UQqo/hq720_2.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGADwAQH4AZQDgALQBYoCDAgAEAEYZSBMKEowDw==&rs=AOn4CLAqtnPKHl1LTu5W6yGhHQ7lbShISQ",
            width: 720,
            height: 404,
          },
          thumbnails: [
            {
              url: "https://i.ytimg.com/vi/Zxxl386UQqo/hq720_2.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGADwAQH4AZQDgALQBYoCDAgAEAEYZSBMKEowDw==&rs=AOn4CLAqtnPKHl1LTu5W6yGhHQ7lbShISQ",
              width: 720,
              height: 404,
            },
            {
              url: "https://i.ytimg.com/vi/Zxxl386UQqo/hq720_2.jpg?sqp=-oaymwE9COgCEMoBSFryq4qpAy8IARUAAAAAGAAlAADIQj0AgKJDeAHwAQH4AZQDgALQBYoCDAgAEAEYZSBMKEowDw==&rs=AOn4CLDvFRZaB8sGYDTl6u9Z37sDyueBpQ",
              width: 360,
              height: 202,
            },
          ],
          isUpcoming: false,
          upcoming: null,
          isLive: false,
          badges: [],
          author: {
            name: "Justin Bieber",
            channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
            url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
            bestAvatar: {
              url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
              width: 68,
              height: 68,
            },
            avatars: [
              {
                url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
                width: 68,
                height: 68,
              },
            ],
            ownerBadges: ["Official Artist Channel"],
            verified: true,
          },
          description: null,
          views: 533848,
          duration: "1:01",
          uploadedAt: "1 year ago",
        },
      ],
    },
    {
      type: "video",
      title: "Justin Bieber - Holy ft. Chance The Rapper",
      id: "pvPsJFRGleA",
      url: "https://www.youtube.com/watch?v=pvPsJFRGleA",
      bestThumbnail: {
        url: "https://i.ytimg.com/vi/pvPsJFRGleA/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAoLXXDtlczw_CDkY7yI45ohGii5A",
        width: 720,
        height: 404,
      },
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/pvPsJFRGleA/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAoLXXDtlczw_CDkY7yI45ohGii5A",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/pvPsJFRGleA/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAF46a29uhW9_9iYxmxGeeGxhFUqA",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: ["CC"],
      author: {
        name: "Justin Bieber",
        channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
        url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: null,
      views: 219201131,
      duration: "5:29",
      uploadedAt: "2 years ago",
    },
    {
      type: "video",
      title: "Justin Bieber: Tiny Desk (Home) Concert",
      id: "Su6kidaGW_8",
      url: "https://www.youtube.com/watch?v=Su6kidaGW_8",
      bestThumbnail: {
        url: "https://i.ytimg.com/vi/Su6kidaGW_8/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLD_klgL_2OzBFGjfMX1z1Gx9xs_nw",
        width: 720,
        height: 404,
      },
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/Su6kidaGW_8/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLD_klgL_2OzBFGjfMX1z1Gx9xs_nw",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/Su6kidaGW_8/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBHlc75-Mn8HK1FkZxUIFY_-VEmzQ",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: [],
      author: {
        name: "NPR Music",
        channelID: "UC4eYXhJI4-7wSWc8UNRwD4A",
        url: "https://www.youtube.com/@nprmusic",
        bestAvatar: {
          url: "https://yt3.ggpht.com/0xQ36bByrRGcbiCG2a6Xb-pft78OAm0GW-5vRjC_uPGWD1mfAK8w7J-IjL4NbZGKbimh3QE1Zg=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/0xQ36bByrRGcbiCG2a6Xb-pft78OAm0GW-5vRjC_uPGWD1mfAK8w7J-IjL4NbZGKbimh3QE1Zg=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Verified"],
        verified: true,
      },
      description: null,
      views: 31348682,
      duration: "15:15",
      uploadedAt: "2 years ago",
    },
    {
      type: "video",
      title: "Justin Bieber - I'll Show You",
      id: "PfGaX8G0f2E",
      url: "https://www.youtube.com/watch?v=PfGaX8G0f2E",
      bestThumbnail: {
        url: "https://i.ytimg.com/vi/PfGaX8G0f2E/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCXBjDEPOMKG6vdtp6nF9SY41sgVw",
        width: 720,
        height: 404,
      },
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/PfGaX8G0f2E/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCXBjDEPOMKG6vdtp6nF9SY41sgVw",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/PfGaX8G0f2E/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDAezk2xZQYvdrkJ3UvAllVFIgInA",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: [],
      author: {
        name: "Justin Bieber",
        channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
        url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: null,
      views: 510770409,
      duration: "3:21",
      uploadedAt: "7 years ago",
    },
    {
      type: "video",
      title:
        "DJ Khaled - I'm The One ft. Justin Bieber, Quavo, Chance the Rapper, Lil Wayne",
      id: "weeI1G46q0o",
      url: "https://www.youtube.com/watch?v=weeI1G46q0o",
      bestThumbnail: {
        url: "https://i.ytimg.com/vi/weeI1G46q0o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAdKnaxawcpoyMakYulUJ4dhyJosw",
        width: 720,
        height: 404,
      },
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/weeI1G46q0o/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAdKnaxawcpoyMakYulUJ4dhyJosw",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/weeI1G46q0o/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBHGta6ZZpVu4Q_fvHForQI4VrodQ",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: ["CC"],
      author: {
        name: "DJ Khaled",
        channelID: "UC0Kgvj5t_c9EMWpEDWJuR1Q",
        url: "https://www.youtube.com/channel/UC0Kgvj5t_c9EMWpEDWJuR1Q",
        bestAvatar: {
          url: "https://yt3.ggpht.com/6rLXl36oQXNCCToi1s2nxiakGsiDlWpJmh0RIL8XQ-K2raRz28R4qSQN-yRqtSIDwR6fFt0i=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/6rLXl36oQXNCCToi1s2nxiakGsiDlWpJmh0RIL8XQ-K2raRz28R4qSQN-yRqtSIDwR6fFt0i=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: null,
      views: 1729238896,
      duration: "5:22",
      uploadedAt: "6 years ago",
    },
    {
      type: "video",
      title: "Justin Bieber - Boyfriend",
      id: "4GuqB1BQVr4",
      url: "https://www.youtube.com/watch?v=4GuqB1BQVr4",
      bestThumbnail: {
        url: "https://i.ytimg.com/vi/4GuqB1BQVr4/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB6bqJLfMqHCpu_jt_WZ1Rm7ue0kA",
        width: 720,
        height: 404,
      },
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/4GuqB1BQVr4/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB6bqJLfMqHCpu_jt_WZ1Rm7ue0kA",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/4GuqB1BQVr4/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDetccwudhld2QlKggA0lKF2BXv_w",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: ["CC"],
      author: {
        name: "Justin Bieber",
        channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
        url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: null,
      views: 872367428,
      duration: "3:31",
      uploadedAt: "11 years ago",
    },
    {
      type: "video",
      title: "Justin Bieber - Love Yourself (PURPOSE : The Movement)",
      id: "oyEuk8j8imI",
      url: "https://www.youtube.com/watch?v=oyEuk8j8imI",
      bestThumbnail: {
        url: "https://i.ytimg.com/vi/oyEuk8j8imI/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDlyO_ZCnEZTQzrSqNhqimQB12TtA",
        width: 720,
        height: 404,
      },
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/oyEuk8j8imI/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDlyO_ZCnEZTQzrSqNhqimQB12TtA",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/oyEuk8j8imI/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCBkrf5_htOaIPmG7JPaowo_-MeEg",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: [],
      author: {
        name: "Justin Bieber",
        channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
        url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: null,
      views: 1704430015,
      duration: "4:33",
      uploadedAt: "7 years ago",
    },
    {
      type: "video",
      title: "Justin Bieber - Beauty And A Beat ft. Nicki Minaj",
      id: "Ys7-6_t7OEQ",
      url: "https://www.youtube.com/watch?v=Ys7-6_t7OEQ",
      bestThumbnail: {
        url: "https://i.ytimg.com/vi/Ys7-6_t7OEQ/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB-h05GLWq-wFrMH-dWFsLu_329yg",
        width: 720,
        height: 404,
      },
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/Ys7-6_t7OEQ/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB-h05GLWq-wFrMH-dWFsLu_329yg",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/Ys7-6_t7OEQ/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA9GnB0kx1K7gaYkLiZcFG10KqK7g",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: ["CC"],
      author: {
        name: "Justin Bieber",
        channelID: "UCIwFjwMjI0y7PDBVEO9-bkQ",
        url: "https://www.youtube.com/channel/UCIwFjwMjI0y7PDBVEO9-bkQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AGIKgqOQZxiUJ4Y5uc9NbKykNt-8BqGc-zKFHX8rjcRUFQ=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: null,
      views: 1044293630,
      duration: "4:53",
      uploadedAt: "10 years ago",
    },
    {
      type: "video",
      title:
        "DJ Khaled ft. Drake - POPSTAR (Official Music Video - Starring Justin Bieber)",
      id: "3CxtK7-XtE0",
      url: "https://www.youtube.com/watch?v=3CxtK7-XtE0",
      bestThumbnail: {
        url: "https://i.ytimg.com/vi/3CxtK7-XtE0/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLD9FC8VLEM86eZAY8awL1-3LgmM2g",
        width: 720,
        height: 404,
      },
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/3CxtK7-XtE0/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLD9FC8VLEM86eZAY8awL1-3LgmM2g",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/3CxtK7-XtE0/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCayvUfMUoWvhzaZ4JZJlo0wIECOw",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: ["CC"],
      author: {
        name: "DJ Khaled",
        channelID: "UC0Kgvj5t_c9EMWpEDWJuR1Q",
        url: "https://www.youtube.com/channel/UC0Kgvj5t_c9EMWpEDWJuR1Q",
        bestAvatar: {
          url: "https://yt3.ggpht.com/6rLXl36oQXNCCToi1s2nxiakGsiDlWpJmh0RIL8XQ-K2raRz28R4qSQN-yRqtSIDwR6fFt0i=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/6rLXl36oQXNCCToi1s2nxiakGsiDlWpJmh0RIL8XQ-K2raRz28R4qSQN-yRqtSIDwR6fFt0i=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: null,
      views: 301120889,
      duration: "8:06",
      uploadedAt: "2 years ago",
    },
    {
      type: "video",
      title: "DJ Snake - Let Me Love You ft. Justin Bieber",
      id: "euCqAq6BRa4",
      url: "https://www.youtube.com/watch?v=euCqAq6BRa4",
      bestThumbnail: {
        url: "https://i.ytimg.com/vi/euCqAq6BRa4/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC9zJRTj3eQtMnGPOT7t0FfItqAQQ",
        width: 720,
        height: 404,
      },
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/euCqAq6BRa4/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC9zJRTj3eQtMnGPOT7t0FfItqAQQ",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/euCqAq6BRa4/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBFGKpPICoCyvt3PmD2dZwdi5Kb5A",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: ["CC"],
      author: {
        name: "DJ Snake",
        channelID: "UC_x8HoD18XJkILQBreVENUQ",
        url: "https://www.youtube.com/channel/UC_x8HoD18XJkILQBreVENUQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/kfw_1eOpjdYASmlAnSPa7XmXrYpaKjuW4k7_oB-hD5ljRSlT7yThew72ZxgW1UrAJ1e8vX1G=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/kfw_1eOpjdYASmlAnSPa7XmXrYpaKjuW4k7_oB-hD5ljRSlT7yThew72ZxgW1UrAJ1e8vX1G=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: null,
      views: 1283097769,
      duration: "3:26",
      uploadedAt: "6 years ago",
    },
  ],
  continuation: null,
  status: true,
};
